export const ADD_ENTRY = 'ADD_ENTRY'
export const SET_USER_ID = 'SET_USER_ID'
export const SET_DATA_LOADED = 'SET_DATA_LOADED'
export const SET_ENTRIES = 'SET_ENTRIES'
export const EDIT_ENTRY = 'EDIT_ENTRY'
export const REMOVE_ENTRY = 'REMOVE_ENTRY'
